sudo: required
dist: xenial    
language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
before_install:
    - sudo add-apt-repository -y ppa:ondrej/php
    - sudo apt-get update -qq
    - sudo apt-get install libzip4 libzip-dev
    - pecl install zip
install: composer install --dev --no-interaction
script: vendor/bin/codecept run unit --coverage --coverage-xml
after_success: travis_retry php vendor/bin/php-coveralls