sudo: required
dist: xenial    
language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
before_install:
    - sudo add-apt-repository -y ppa:ondrej/php
    - sudo apt-get update -qq
    - sudo apt-get install libzip4
    - pecl install zip
install: composer install
script: vendor/bin/codecept run